#define MACHINE      "(unknown)"
#define MAKE_VERSION "20240625"
typedef unsigned long DWORD;
#include "src/arch.c"
#include "src/buf.c"
#include "src/compat.c"
#include "src/cond.c"
#include "src/dir.c"
#include "src/dirname.c"
#include "src/for.c"
#include "src/hash.c"
#include "src/job.c"
#include "src/lst.c"
#include "src/main.c"
#include "src/make.c"
#include "src/make_malloc.c"
#include "src/message.c"
#include "src/meta.c"
#include "src/parse.c"
#include "src/str.c"
#include "src/stresep.c"
#include "src/strlcpy.c"
#include "src/suff.c"
#include "src/targ.c"
#include "src/trace.c"
#include "src/util.c"
#include "src/var.c"
